### ISSUE TITLE
org.apache.spark.internal.Logging issue

### ISSUE THREAD

**Issue by shashankmodi** [cloudera-labs/envelope#44]
Hi,
I am using spark 2.4 version, please help me soon.
I am getting error org.apache.spark.internal.Logging.

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at com.dell.sadatahub.azure.utils.SingletonSparkSession.getSparkSession(SingletonSparkSession.scala:26)
	at com.dell.sadatahub.azure.DDVJsonParser$.main(DDVJsonParser.scala:15)
	at com.dell.sadatahub.azure.DDVJsonParser.main(DDVJsonParser.scala)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.internal.Logging
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 15 more

**Comment by jeremybeard** [comment]
Is this using Envelope? I don't see Envelope classes in the stack trace.

**Comment by shashankmodi** [comment]
no enevelop....

**Comment by shashankmodi** [comment]
what can be the cause of this error..I need to solve this early

**Comment by jeremybeard** [comment]
This page is for issues with Envelope, not general Spark assistance. Please ask your question to the Apache Spark mailing lists, or if you have commercial support for Spark then contact your software vendor.
